export { MainPage as SettingsMainPage } from './src/main/ets/components/Settings_MainPage';
export { DataSourceSettings } from './src/main/ets/views/DataSource/DataSourceSettings';
export { DisplaySettings } from './src/main/ets/views/DisplaySettings/DisplaySettings';
export { PlaybackSettings } from './src/main/ets/views/PlaybackSettings/PlaybackSettings';
export { PlayStatistics } from './src/main/ets/views/PlayStatistics/PlayStatistics';
