export { AlbumAPIUtils as Cloud_AlbumAPIUtils } from '@handwer/cloud_api';
export { ArtistAPIUtils as Cloud_ArtistAPIUtils } from '@handwer/cloud_api';
export { CommentAPIUtils as Cloud_CommentAPIUtils } from '@handwer/cloud_api';
export { DjAPIUtils as Cloud_DjAPIUtils } from '@handwer/cloud_api';
export { LoginAPIUtils as Cloud_LoginAPIUtils } from '@handwer/cloud_api';
export { LyricAPIUtils as Cloud_LyricAPIUtils } from '@handwer/cloud_api';
export { PlayListAPIUtils as Cloud_PlayListAPIUtils } from '@handwer/cloud_api';
export { SongAPIUtils as Cloud_SongAPIUtils } from '@handwer/cloud_api';
export { TopListAPIUtils as Cloud_TopListAPIUtils } from '@handwer/cloud_api';

export { User as CloudUser } from '@handwer/cloud_api' // 防止 structural typing
