export enum SCPref {
  theme = 'theme',
  notFirstOpen = 'notFirstOpen',
  cacheSet = 'cacheSet',
  audioQuality = 'audioQuality',

  apiInstanceType = 'apiInstanceType',
  currentAPIConfig = 'currentAPIConfig',

  useMissionContinue = 'useMissionContinue',

  // 显示设置
  showPlayerOnLaunch = 'showPlayerOnLaunch',
  showMusicLibraryInOnlineMusic = 'showMusicLibraryInOnlineMusic',
  navigationRightHandMode = 'navigationRightHandMode',
  autoNavRightHand = 'autoNavRightHand',
  playerTwoColumnRightHandMode = 'playerTwoColumnRightHandMode',
  dynamicBackgroundStreaming = 'dynamicBackgroundStreaming',
  bgFlowColorStrat = 'bgFlowColorStrat',
  appColorMode = "appColorMode",

  // 播放设置
  autoPlayOnLaunch = 'autoPlayOnLaunch',
  autoPlayFM = 'autoPlayFM',
  useStylusControl = 'useStylusControl',
  swipeToNextTrack = 'swipeToNextTrack',
  fistGesture = "fistGesture"
}